# Generated by Django 5.2 on 2025-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='title_text',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='create_date',
        ),
        migrations.AddField(
            model_name='info',
            name='password',
            field=models.CharField(default='abcd1234', max_length=100),
        ),
    ]
