# Generated by Django 5.2 on 2025-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_title_text_info_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('admin_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='user_name',
            field=models.CharField(default='홍길동', max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
