# Generated by Django 5.2 on 2025-05-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_admin_info_user_name_alter_info_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admin_Login',
        ),
        migrations.RenameModel(
            old_name='Info',
            new_name='User_Login',
        ),
    ]
