# Generated by Django 5.2 on 2025-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_admin_admin_login_rename_info_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('work_start', models.DateTimeField()),
                ('work_end', models.DateTimeField()),
                ('total_time', models.DurationField()),
                ('work_date', models.DateField()),
                ('work_place', models.CharField(max_length=100)),
            ],
        ),
    ]
