# Generated by Django 5.2 on 2025-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_work_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_info',
            name='total_time',
            field=models.CharField(),
        ),
    ]
