# Generated by Django 5.1.7 on 2025-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_work_info_total_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work_info",
            name="total_time",
            field=models.CharField(max_length=20),
        ),
    ]
