# Generated by Django 5.2 on 2025-05-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_work_info_total_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Number', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Daily_Wages', models.IntegerField()),
            ],
        ),
    ]
