# Generated by Django 5.1.7 on 2025-05-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_work_info_total_time"),
        ("myapp", "0007_work_pay"),
    ]

    operations = []
