# Generated by Django 5.2 on 2025-05-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_work_info_total_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login_Info',
            fields=[
                ('employee_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='홍길동', max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('daily_wages', models.IntegerField()),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_login_info')),
            ],
        ),
        migrations.RenameModel(
            old_name='Admin_Login',
            new_name='Admin_Login_Info',
        ),
        migrations.DeleteModel(
            name='User_Login',
        ),
        migrations.AddField(
            model_name='work_info',
            name='employee_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_login_info'),
            preserve_default=False,
        ),
    ]
