# Generated by Django 5.2 on 2025-06-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_login_info_work_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login_info',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login_info',
            name='resident_number',
            field=models.CharField(default=12, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_login_info',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
