# Generated by Django 5.1.7 on 2025-05-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_merge_0007_alter_work_info_total_time_0007_work_pay"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Login_Info",
            fields=[
                (
                    "work_num",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(default="홍길동", max_length=50)),
                ("user_id", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Admin_Login",
            new_name="Admin_Login_Info",
        ),
        migrations.DeleteModel(
            name="User_Login",
        ),
        migrations.RemoveField(
            model_name="work_info",
            name="id",
        ),
        migrations.RemoveField(
            model_name="work_pay",
            name="id",
        ),
        migrations.AddField(
            model_name="work_info",
            name="work_num",
            field=models.CharField(
                default=0, max_length=50, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="work_pay",
            name="work_num",
            field=models.CharField(
                default=0, max_length=50, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
