# Generated by Django 5.2 on 2025-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_login_info_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login_info',
            name='mobile_carrier',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
