# Generated by Django 5.1.7 on 2025-05-30 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_user_login_info_rename_admin_login_admin_login_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work_info",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="work_pay",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="work_info",
            name="work_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.user_login_info"
            ),
        ),
        migrations.AlterField(
            model_name="work_pay",
            name="work_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.user_login_info"
            ),
        ),
    ]
