# Generated by Django 5.2 on 2025-06-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_login_info_mobile_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login_info',
            name='address',
            field=models.CharField(default='seosan', max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='user_login_info',
            constraint=models.UniqueConstraint(fields=('employee_number',), name='unique_employee_number'),
        ),
        migrations.AddConstraint(
            model_name='user_login_info',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_user_id'),
        ),
        migrations.AddConstraint(
            model_name='user_login_info',
            constraint=models.UniqueConstraint(fields=('resident_number',), name='unique_resident_number'),
        ),
        migrations.AddConstraint(
            model_name='user_login_info',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_phone_number'),
        ),
    ]
