# Generated by Django 5.1.7 on 2025-05-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_work_info_id_work_pay_id_alter_work_info_work_num_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_login_info",
            old_name="work_num",
            new_name="employee_number",
        ),
        migrations.RenameField(
            model_name="work_info",
            old_name="work_num",
            new_name="employee_number",
        ),
        migrations.RenameField(
            model_name="work_pay",
            old_name="Company",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="work_pay",
            old_name="Daily_Wages",
            new_name="daily_wages",
        ),
        migrations.RenameField(
            model_name="work_pay",
            old_name="work_num",
            new_name="employee_number",
        ),
        migrations.RemoveField(
            model_name="work_pay",
            name="Employee_Number",
        ),
    ]
